<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Label="Analyzer relaxations">
    <!-- CA1707: underscores in identifiers. -->
    <!-- CA:2007: ConfigureAwait. No synchronization context in a test host. -->
    <NoWarn>$(NoWarn);CA1707;CA2007</NoWarn>
  </PropertyGroup>
</Project>
