// <auto-generated />
using System;
using Hookwright.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hookwright.SqlServer.Migrations
{
    [DbContext(typeof(HookwrightDbContext))]
    [Migration("20260917222019_AddRetentionIndexes")]
    partial class AddRetentionIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hookwright.Core.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("endpoint_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("lease_owner")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("partition_key")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_hookwright_deliveries_completed_at");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_hookwright_deliveries_event_id");

                    b.HasIndex("EndpointId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_hookwright_deliveries_endpoint_id_created_at");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("ix_hookwright_deliveries_state_next_attempt_at");

                    b.ToTable("hookwright_deliveries", (string)null);
                });

            modelBuilder.Entity("Hookwright.Core.Deliveries.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("attempted_at");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("delivery_id");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("error_detail")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint")
                        .HasColumnName("outcome");

                    b.Property<string>("ResponseBodySnippet")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_body_snippet")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("response_status_code");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("worker_id")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("_responseHeaders")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_headers");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .HasDatabaseName("ix_hookwright_delivery_attempts_attempted_at");

                    b.HasIndex("DeliveryId", "AttemptedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_hookwright_delivery_attempts_delivery_id_attempted_at");

                    b.ToTable("hookwright_delivery_attempts", (string)null);
                });

            modelBuilder.Entity("Hookwright.Core.Endpoints.EndpointSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<short>("Algorithm")
                        .HasColumnType("smallint")
                        .HasColumnName("algorithm");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("ProtectedKey")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("protected_key")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId", "ValidUntil")
                        .HasDatabaseName("ix_hookwright_endpoint_secrets_endpoint_id_valid_until");

                    b.ToTable("hookwright_endpoint_secrets", (string)null);
                });

            modelBuilder.Entity("Hookwright.Core.Endpoints.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("int")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisabledReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("disabled_reason")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<short>("Health")
                        .HasColumnType("smallint")
                        .HasColumnName("health");

                    b.Property<short>("PartitionMode")
                        .HasColumnType("smallint")
                        .HasColumnName("partition_mode");

                    b.Property<int?>("RateLimitPerSecond")
                        .HasColumnType("int")
                        .HasColumnName("rate_limit_per_second");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscriber_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("url");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("verified_at");

                    b.PrimitiveCollection<string>("_eventTypeFilter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("event_type_filter");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberId", "Health")
                        .HasDatabaseName("ix_hookwright_endpoints_subscriber_id_health");

                    b.ToTable("hookwright_endpoints", (string)null);
                });

            modelBuilder.Entity("Hookwright.Core.Events.EventType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<string>("SchemaJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("schema_json")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Name");

                    b.ToTable("hookwright_event_types", (string)null);
                });

            modelBuilder.Entity("Hookwright.Core.Events.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("idempotency_key")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("partition_key")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscriber_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("_headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("headers");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hookwright_events_created_at");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("ix_hookwright_events_idempotency_key");

                    b.HasIndex("SubscriberId", "Id")
                        .HasDatabaseName("ix_hookwright_events_subscriber_id_id");

                    b.ToTable("hookwright_events", (string)null);
                });

            modelBuilder.Entity("Hookwright.Core.Subscribers.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("disabled_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("external_id")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_hookwright_subscribers_external_id");

                    b.ToTable("hookwright_subscribers", (string)null);
                });

            modelBuilder.Entity("Hookwright.Core.Deliveries.Delivery", b =>
                {
                    b.HasOne("Hookwright.Core.Endpoints.WebhookEndpoint", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hookwright.Core.Events.WebhookEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hookwright.Core.Deliveries.DeliveryAttempt", b =>
                {
                    b.HasOne("Hookwright.Core.Deliveries.Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hookwright.Core.Endpoints.EndpointSecret", b =>
                {
                    b.HasOne("Hookwright.Core.Endpoints.WebhookEndpoint", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hookwright.Core.Endpoints.WebhookEndpoint", b =>
                {
                    b.HasOne("Hookwright.Core.Subscribers.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hookwright.Core.Events.WebhookEvent", b =>
                {
                    b.HasOne("Hookwright.Core.Subscribers.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
